/**
 * @swagger
 * components:
 *   schemas:
 *     Notification:
 *       type: object
 *       required:
 *         - userid
 *         - message
 *         - time
 *         - chatid
 *
 *       properties:
 *         notificationid:
 *           type: integer
 *           description: The autogenerated ID of the user.
 *         userid:
 *           type: integer
 *           description: The id of the user who sent the message.
 *         chatid:
 *           type: integer
 *           description: The id of the chat the message belongs to.
 *         message:
 *           type: string
 *           description: The content of the message.
 *         time:
 *           type: string
 *           description: The time the message was sent.
 *
 */
import express from "express";
import { Notification } from "../domain/model/notification";
import notificationService from "../service/notification.service";
const router = express.Router();


/**
 * @swagger
 * tags:
 *  name: Notifications
 *  description: The notification managing API
 */

/**
 * @swagger
 * /notification:
 *   get:
 *     summary: Returns all notifications
 *     tags: [Notifications]
 *     responses:
 *       200:
 *         description: A list of notifications
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Notification'
 *       500:
 *         description: Internal server error
 */

router.get("/", async (req, res) => {
    try {
        const messages = await notificationService.getAllNotifications();
        res.status(200).json(messages)
    } catch(error) {
        res.status(500).json({status: 'error', errorMessage: error.message})
    }
})

export default router;